# Generated by Django 5.0.4 on 2024-05-03 13:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnimalType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lifespan', models.CharField(max_length=128)),
                ('type', models.CharField(max_length=64)),
                ('breed', models.CharField(choices=[('CAT', 'Cat'), ('DOG', 'Dog')], max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=128)),
                ('last_name', models.CharField(max_length=128)),
                ('oib', models.CharField(max_length=11)),
                ('adress', models.CharField(max_length=128)),
                ('city', models.CharField(max_length=64)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('age', models.SmallIntegerField(default=5)),
                ('description', models.CharField(max_length=1024)),
                ('height', models.CharField(max_length=64)),
                ('weight', models.CharField(max_length=64)),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.animaltype')),
                ('adopted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.user')),
            ],
        ),
        migrations.CreateModel(
            name='AdoptingRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('DECLINED', 'Declined')], max_length=10)),
                ('animal_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.animal')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.user')),
            ],
        ),
    ]
