# Generated by Django 5.0.4 on 2024-05-21 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_animal_avatar_url_user_avatar_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animaltype',
            name='breed',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='animaltype',
            name='type',
            field=models.CharField(choices=[('CAT', 'Cat'), ('DOG', 'Dog')], max_length=64),
        ),
    ]
