# Generated by Django 5.0.4 on 2024-05-21 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_animaltype_breed_alter_animaltype_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='adopted_by',
            field=models.BooleanField(default=False),
        ),
    ]
