# Generated by Django 5.0.4 on 2024-05-21 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_animal_adopted_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='animal',
            old_name='adopted_by',
            new_name='is_adopted',
        ),
    ]
