# Generated by Django 5.0.4 on 2024-05-29 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_user_options_alter_user_managers_animal_gender_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adoptingrequest',
            old_name='animal_id',
            new_name='animal',
        ),
        migrations.RenameField(
            model_name='adoptingrequest',
            old_name='user_id',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
