# Generated by Django 5.0.4 on 2024-06-05 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_rename_animal_adoptingrequest_animal_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='adoptingrequest',
            name='description',
            field=models.CharField(blank=True, max_length=3000, null=True),
        ),
    ]
